### ISSUE TITLE
Transport?

### ISSUE THREAD

**Issue by auser** [Dempsy/dempsy#50]
Hey guys,

I see that the transport for TCP has been implemented. Curious to know if/when a netty or zeromq transport is planned?

Thanks

**Comment by jimfcarroll** [comment]
Netty sucks and is much slower than the current NioTransport. I was going to move it (the NettyTransport) to dempsy-additions. I had a 0mq available for 0.8 but I'm not sure I'll ever port it to 0.9 since it seems superfluous.
